version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8083:80"
    depends_on:
      - app
    container_name: crm_nginx

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: crm_app


  db:
   image: mysql:8.0
   restart: always
   volumes:
       - ./tmp/db:/var/lib/mysql
       - ./_docker/my.cnf:/etc/mysql/my.conf
   environment:
       MYSQL_DATABASE: laravel
       MYSQL_ROOT_PASSWORD: root
   ports:
       - "3308:3306"
   #command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

   container_name: crm_db

  node:
    build:
        context: .
        dockerfile: _docker/nodejs/Dockerfile
    volumes:
        - ./:/var/www
    container_name: crm_node
  
